### PR TITLE
Update gtk-3.mustache

### PR DESCRIPTION
**Pull request by notginned**
Add missing colors that are assigned in FlatColor gtk-3.2 css file.

### CODE REVIEW

**Comment by notginned** [comment]
Also changed README.md to fix importing issue with gtk-3 and gtk-3.2 themes.

**Comment by Misterio77** [comment]
Hey, nice catch on the readme.

About the color defines, i _think_ we don't need them.

The colors from 0 to 15 are only actually used on these definitions:
```
selected_bg_color
bg_color mix
tooltip_bg_color
base_color
fg_color
text_color
text_color_disabled
selected_fg_color
tooltip_fg_color
```

Which are already covered in the template.

**Comment by notginned** [comment]
> About the color defines, i _think_ we don't need them.

You're right, I took a quick look at the theme css file and couldn't really find the colors used somewhere but I guessed they may have had some use.

I did find that we haven't specified an appropriate color for `text_color_disabled` yet. Dunno if it's useful or not though.

**Comment by Misterio77** [comment]
Oh right, forgot about that one haha. I think it didn't cause any visible issues, but should be nice to have. Feel free to add it in your fork before i merge, if you want. Or else i can merge this as is and add it myself

**Comment by Misterio77** [comment]
Thanks for the fixes and input ❤

**Comment by notginned** [comment]
I added it as `base03` as `text_disabled_color` since the base16 spec says it's for comments, guess that'll be more than enough? I didn't find any problems without defining it myself so far either.

**Comment by notginned** [comment]
> Thanks for the fixes and input :heart:

Thank you for your wonderful project :heart:  ! 
It took me a whole day to get the hang of, but it's really straightforward and pretty damn fast once you do.

I've migrated most of my configs from pywal already, and I look forward to helping this project grow in any way I can!

**Comment by Misterio77** [comment]
Looking great!

Thank you for giving it a try and helping out, glad something i built could be useful 😍

**Pull request merged**
